/**
 * 英文小詞典：元素知識裡的英文句子，點任何一個字都能看到繁中翻譯。
 * 句子中用 `word|中文` 標註的字優先，標註不到的就來這裡查。
 */
const DICT: Record<string, string> = {
  // 節日 / 名勝 / 港鐵 / 天氣 四個新遊戲用到的字
  ask: "要；請求",
  blow: "吹",
  bring: "帶",
  climbs: "爬上去",
  coming: "來臨",
  cover: "遮住",
  crosses: "橫渡",
  decorate: "佈置",
  drink: "喝",
  during: "在⋯⋯的時候",
  eat: "吃",
  guess: "猜",
  whole: "整個",
  happy: "快樂的",
  lived: "住過",
  open: "打開",
  beijing: "北京",
  hong: "香港（Hong Kong 香港的 Hong）",
  kong: "港（Hong Kong 香港的 Kong）",
  victoria: "維多利亞",
  west: "西",
  night: "夜晚",
  mountains: "群山",
  palace: "宮殿",
  ride: "乘坐",
  sha: "沙（Tsim Sha Tsui 尖沙咀的 Sha）",
  stand: "站立",
  stayed: "居住過",
  theme: "主題",
  tsim: "尖（Tsim Sha Tsui 尖沙咀的 Tsim）",
  wall: "城牆",
  "xi'an": "西安",
  across: "跨越",
  atomic: "原子的",
  bit: "一點點",
  came: "來自",
  cannot: "不能",
  control: "控制",
  gets: "得到",
  her: "她的",
  holding: "拿著",
  less: "少於",
  nearby: "附近的",
  room: "房間",
  shining: "閃亮",
  street: "街頭",
  swimming: "游泳",
  thanks: "多虧",
  their: "它們的",
  turned: "變成",
  until: "直到",
  without: "沒有",
  would: "將會",

  above: "在高空",
  acids: "酸",
  act: "表現",
  actinide: "錒系",
  actinium: "錒",
  advertised: "宣稱",
  ago: "很久以前",
  airplanes: "飛機",
  albert: "阿爾伯特",
  alchemy: "煉金",
  alfred: "阿爾弗雷德",
  alive: "在世",
  alpha: "阿爾法",
  aluminium: "鋁",
  america: "美國",
  americas: "美洲",
  americium: "鋂",
  among: "在",
  amounts: "份量",
  anesthetic: "麻醉劑",
  animals: "動物",
  another: "另一",
  antimony: "銻",
  argon: "氬",
  argued: "爭論",
  armor: "外殼",
  arsenic: "砷",
  ash: "灰",
  asia: "亞洲",
  astatine: "砈",
  asteroid: "小行星",
  astronaut: "太空人",
  backed: "鍍上",
  ball: "球",
  barium: "鋇",
  basements: "地下室",
  baths: "槽",
  beach: "海灘",
  beads: "珠",
  beat: "跳動",
  beaten: "捶薄",
  been: "被",
  behave: "表現",
  bend: "彎",
  berkeley: "柏克萊",
  berkelium: "鉳",
  beryl: "綠柱石",
  beryllium: "鈹",
  between: "在之間",
  beyond: "超過",
  bike: "腳踏車",
  bismuth: "鉍",
  bits: "份量",
  blades: "刃",
  blazing: "熾熱",
  blink: "一眨眼",
  blood: "血液",
  bohr: "波耳",
  bohrium: "𨨏",
  boiling: "沸騰",
  bomb: "彈",
  boom: "爆炸",
  boosts: "放大",
  boron: "硼",
  breath: "口氣",
  bromine: "溴",
  bronze: "青銅",
  built: "建造",
  burning: "繼續燒",
  butter: "奶油",
  cadmium: "鎘",
  caesium: "銫",
  calcium: "鈣",
  californium: "鉲",
  camping: "露營",
  cancer: "癌症",
  carbon: "碳",
  carved: "刻出",
  catalytic: "觸媒",
  catch: "吸收",
  caves: "洞穴",
  cent: "分",
  center: "中心",
  centuries: "好幾世紀",
  cerium: "鈰",
  chalk: "粉筆",
  charcoal: "木炭",
  chemistry: "化學",
  chicago: "芝加哥",
  chlorine: "氯",
  chlorophyll: "葉綠素",
  chromium: "鉻",
  chunks: "塊",
  cities: "大城市",
  clad: "包覆",
  claimed: "宣稱",
  cleaner: "乾淨",
  clearly: "清晰",
  closes: "收尾",
  coal: "煤炭",
  coat: "外衣",
  coated: "塗著",
  coats: "包著",
  cobalt: "鈷",
  common: "常見",
  considered: "考慮",
  contacts: "接點",
  continent: "大洲",
  converters: "轉換器",
  copenhagen: "哥本哈根",
  copernicium: "鎶",
  copernicus: "哥白尼",
  core: "地核",
  costs: "值",
  could: "可能",
  cousin: "親戚",
  crackles: "喀喀响",
  create: "合成",
  creator: "創造者",
  crowns: "牙冠",
  crust: "地殼",
  cry: "鳴叫",
  curie: "居禮",
  curies: "居禮夫婦",
  curium: "鋦",
  cut: "切",
  cuts: "傷口",
  cyclotron: "迴旋加速器",
  dandruff: "頭皮屑",
  darmstadt: "達姆施塔特",
  darmstadtium: "𨨏",
  date: "測定",
  debris: "殘骸",
  decays: "衰變",
  deep: "深",
  defined: "定義",
  densest: "最密",
  detectors: "偵測器",
  dials: "錶面",
  different: "不同",
  discover: "發現",
  discovered: "被發現",
  discovery: "發現",
  double: "雙層",
  drew: "繪製",
  drinks: "飲料",
  dubna: "杜布納",
  dubnium: "𨧀",
  dust: "灰塵",
  dysprosium: "鏑",
  egyptians: "埃及人",
  einstein: "愛因斯坦",
  einsteinium: "鑀",
  electric: "電動",
  electrical: "電子",
  electrons: "電子",
  emeralds: "祖母綠",
  engineer: "工程師",
  enrico: "恩里科",
  enzymes: "酵素",
  equals: "等於",
  erbium: "鉺",
  ernest: "歐內斯特",
  europe: "歐洲",
  europium: "銪",
  even: "即使",
  ever: "曾",
  exists: "存在",
  explained: "解釋",
  explodes: "爆炸",
  extinction: "滅絕",
  extra: "額外",
  eye: "眼睛",
  fades: "衰變",
  fading: "衰變",
  faintly: "微弱",
  famous: "有名",
  feels: "摸起來",
  fermi: "費米",
  fermium: "鐨",
  fiber: "光纖",
  filaments: "燈絲",
  filled: "灌滿",
  fills: "填充",
  film: "底片",
  filter: "濾網",
  fingertip: "指尖",
  firework: "煙火",
  firing: "轟擊",
  first: "先",
  fish: "魚",
  fission: "分裂",
  fit: "放得進",
  five: "伍",
  fix: "治",
  flame: "火焰",
  flashes: "閃光燈",
  flerov: "弗廖羅夫",
  flerovium: "鈇",
  flints: "火石",
  floated: "浮著",
  fluorine: "氟",
  fly: "飛",
  forms: "形態",
  "fortune-teller": "算命師",
  fountain: "鋼筆",
  frames: "車架",
  france: "法國",
  francium: "鍅",
  frozen: "凝固的",
  fumes: "廢氣",
  funny: "有趣",
  gadolinium: "釓",
  gallium: "鎵",
  garlic: "蒜",
  gems: "寶石",
  gentle: "溫和",
  gently: "溫和",
  german: "德國",
  germanium: "鍺",
  germs: "細菌",
  get: "取得",
  ghost: "幽影",
  giant: "巨大的",
  gills: "鰓",
  girls: "女孩",
  glasses: "玻璃",
  glenn: "格倫",
  glowing: "發光",
  god: "神",
  goggles: "護目鏡",
  gps: "定位",
  grabs: "搶",
  gram: "一克",
  grams: "克",
  graphite: "石墨",
  great: "很棒",
  greek: "希臘",
  ground: "地面",
  grow: "長大",
  grows: "長出",
  guessed: "猜中",
  gunpowder: "火藥",
  hafnium: "鉿",
  half: "一半",
  halogen: "鹵素",
  handlebars: "把手",
  hands: "牽著",
  hardest: "最硬",
  hassium: "𨭆",
  hates: "不怕",
  headphones: "耳機",
  heads: "頭",
  healthy: "健康",
  heart: "心臟",
  "heat-proof": "耐熱",
  heats: "受熱",
  helium: "氦氣",
  helmets: "頭盔",
  hesse: "黑森",
  hidden: "藏在",
  hides: "藏在",
  hiding: "藏",
  highest: "最高",
  hold: "固定",
  holmium: "鈥",
  homeland: "祖國",
  hundred: "一百",
  hungry: "活潑",
  hunt: "追尋",
  hunted: "追尋",
  hunting: "追尋",
  hybrid: "油電車",
  hydrogen: "氫氣",
  ignores: "不排斥",
  indigo: "靛藍",
  indium: "銦",
  invented: "發明",
  iodine: "碘",
  ion: "離子",
  ions: "離子",
  iridium: "銥",
  island: "島",
  japanese: "日本",
  jet: "噴射",
  joke: "玩笑",
  keeps: "讓",
  kilograms: "公斤",
  king: "國王",
  knights: "騎士",
  krypton: "氪",
  labs: "實驗室",
  land: "之地",
  lanthanide: "鑭系",
  lanthanum: "鑭",
  laundry: "洗衣粉",
  lawrence: "勞倫斯",
  lawrencium: "鐒",
  layer: "地層",
  lazy: "惰性",
  lead: "筆芯",
  leaf: "金箔",
  leaves: "葉子",
  leaving: "離開",
  led: "燈",
  liberty: "自由",
  lift: "吸起",
  lighthouses: "燈塔",
  lightning: "閃電",
  lights: "點亮",
  lilac: "淡紫色",
  line: "紅線",
  lise: "莉澤",
  lithium: "鋰",
  litre: "公升",
  livermore: "利弗莫爾",
  livermorium: "鉝",
  living: "在世",
  longer: "更久",
  looking: "觀察",
  loud: "大聲",
  love: "喜歡",
  loved: "愛用",
  lump: "塊",
  lutetium: "鎦",
  magnesium: "鎂",
  magnetic: "磁性",
  makeup: "化妝品",
  "man-made": "人造",
  manganese: "錳",
  mantles: "紗罩",
  map: "星圖",
  marguerite: "瑪格麗特",
  marie: "瑪麗",
  marks: "標記",
  mars: "火星",
  maybe: "可能",
  meitner: "邁特納",
  meitnerium: "䥑",
  mendeleev: "門得列夫",
  mendelevium: "鍆",
  mercury: "汞",
  meteorites: "隕石",
  meter: "公尺",
  might: "可能",
  milkshake: "顯影劑",
  millions: "數百萬",
  millisecond: "一毫秒",
  mine: "礦坑",
  mischmetal: "混合稀土",
  mistaken: "被誤認",
  mix: "混合",
  mixed: "混合",
  mixes: "混合",
  molybdenum: "鉬",
  moments: "片刻",
  moscovium: "鏌",
  moscow: "莫斯科",
  move: "動起來",
  moved: "移動",
  mri: "磁振造影",
  muscles: "肌肉",
  mystery: "謎",
  mythical: "傳說",
  nails: "釘子",
  natural: "天然",
  need: "需要",
  needs: "需要",
  neodymium: "釹",
  neon: "氖",
  neptune: "海王星",
  neptunium: "錼",
  neutrons: "中子",
  nickel: "鎳",
  nicknamed: "暱稱",
  niels: "尼爾斯",
  nihon: "日本",
  nihonium: "鉨",
  nine: "九年",
  niobium: "鈳",
  nitrogen: "氮氣",
  nobelium: "鍩",
  noble: "惰性",
  "non-stick": "不沾鍋",
  notebooks: "筆記",
  ntgen: "倫琴",
  ocean: "海洋",
  oceans: "跨洋",
  oganessian: "奧加涅相",
  oganesson: "鿫",
  oil: "油",
  once: "曾經",
  ore: "礦石",
  osmium: "鋨",
  overlooked: "被忽略",
  own: "自身",
  oxygen: "氧",
  ozone: "臭氧",
  painted: "畫滿",
  painters: "古人",
  pale: "淡",
  palladium: "鈀",
  panels: "板",
  paper: "紙",
  particles: "粒子",
  party: "派對",
  pellet: "燃料丸",
  pen: "鋼筆",
  pencil: "鉛筆",
  penny: "壹分銅幣",
  people: "人",
  per: "每",
  perey: "佩雷",
  pet: "正子掃描",
  phosphors: "螢光粉",
  phosphorus: "磷",
  photocells: "光電池",
  photography: "攝影",
  photos: "拍攝",
  physics: "物理",
  pictures: "影像",
  pinch: "一點碘",
  planet: "行星",
  plastic: "塑膠",
  plated: "鍍",
  platinum: "鉑",
  plugs: "火星塞",
  pluto: "冥王星",
  plutonium: "鈽",
  pointers: "筆",
  poison: "毒藥",
  poland: "波蘭",
  polishes: "拋光",
  polonium: "釙",
  pond: "池塘",
  portable: "手提",
  potassium: "鉀",
  pots: "壺",
  powder: "粉末",
  powered: "驅動",
  praseodymium: "鐠",
  priciest: "最貴",
  princess: "公主",
  prizes: "獎項",
  probes: "探測器",
  promethium: "鉅",
  prospectors: "探礦者",
  protactinium: "鏷",
  protection: "防護",
  pull: "拉力",
  pure: "純",
  purple: "紫色",
  push: "推進",
  puzzle: "謎題",
  quarry: "採石場",
  radiation: "輻射",
  radium: "鐳",
  radon: "氡",
  rain: "雨水",
  rarer: "比",
  rat: "老鼠",
  reactive: "活潑",
  reactors: "反應爐",
  reacts: "反應",
  read: "讀",
  "red-orange": "橘紅色",
  reflect: "反射",
  region: "地區",
  reliable: "可靠",
  resistant: "耐腐蝕",
  retardants: "阻燃劑",
  rhenium: "錸",
  rhodium: "銠",
  rockets: "火箭",
  rocky: "多岩",
  rod: "棒",
  rods: "棒",
  roentgenium: "𩬍",
  roll: "滾",
  roman: "羅馬",
  rotten: "臭",
  rover: "探測車",
  row: "一排",
  rubidium: "銣",
  rubies: "紅寶石",
  ruby: "紅寶石",
  russian: "俄羅斯",
  "rust-free": "不生鏽",
  rusting: "生鏽",
  ruthenium: "釕",
  rutherford: "拉塞福",
  rutherfordium: "鑪",
  s: "地球",
  samarium: "釤",
  same: "同一",
  sand: "沙子",
  sandwich: "三明治",
  sank: "沉",
  sb: "銻",
  scandium: "鈧",
  science: "科學",
  scottish: "蘇格蘭",
  sea: "海洋",
  seaborg: "西博格",
  seaborgium: "𨭎",
  seashells: "貝殼",
  seaweed: "海藻",
  seconds: "幾秒",
  sediments: "沉積物",
  seeps: "滲出",
  selenium: "硒",
  "self-heating": "自發熱",
  shampoo: "洗髮精",
  sharp: "刺鼻",
  shiny: "閃亮",
  shrugs: "不怕",
  shy: "害羞",
  signs: "招牌",
  silicon: "矽",
  sits: "坐",
  size: "大小",
  skies: "夜空",
  sky: "天空",
  smashing: "撞擊",
  smelliest: "最臭",
  sniff: "探測",
  sodium: "鈉",
  sofas: "沙發",
  sonar: "聲納",
  sound: "音質",
  sounds: "聽起來",
  spacecraft: "太空船",
  sparkle: "閃爍",
  spas: "溫泉",
  spent: "花了",
  spoons: "湯匙",
  springy: "有彈性",
  squeaks: "吱吱叫",
  stability: "穩定之島",
  stable: "穩定",
  stack: "堆疊",
  stadium: "體育館",
  staircase: "階梯",
  start: "啟動",
  statue: "雕像",
  steady: "平穩",
  still: "仍然",
  stink: "惡臭",
  stomach: "胃",
  stone: "重石頭",
  store: "儲存",
  stories: "故事",
  strength: "力量",
  stronger: "更硬",
  strontium: "鍶",
  studied: "研究",
  study: "研究",
  submarines: "潛水艇",
  sulfur: "硫",
  sun: "太陽",
  sunlight: "陽光",
  sunscreen: "防曬乳",
  sunshine: "陽光",
  superconduct: "超導",
  superconductors: "超導體",
  surgery: "手術",
  survives: "存活",
  sweden: "瑞典",
  swedish: "瑞典",
  sword: "劍",
  symbol: "符號",
  system: "系統",
  systems: "系統",
  tantalum: "鉭",
  tantalus: "坦塔羅斯",
  targeted: "標靶",
  team: "團隊",
  technetium: "鎝",
  telescopes: "太空望遠鏡",
  tellurium: "碲",
  temperature: "室溫",
  ten: "十",
  tennessee: "田納西",
  tennessine: "Ts",
  terbium: "鋱",
  test: "試驗",
  thallium: "鉈",
  therapy: "治療",
  thermometers: "溫度計",
  thin: "薄層",
  things: "東西",
  think: "認為",
  thor: "索爾",
  thorium: "釷",
  three: "三",
  thule: "圖勒",
  thulium: "銩",
  thunder: "雷神",
  thyroid: "甲狀腺",
  times: "倍",
  tin: "錫",
  tips: "筆尖",
  titanium: "鈦",
  today: "今天",
  ton: "噸",
  tons: "噸",
  toothpaste: "牙膏",
  tough: "堅固",
  town: "小鎮",
  toxic: "有毒",
  toys: "玩具",
  transistor: "電晶體",
  trapped: "被封在",
  treatments: "治療",
  tubes: "玻璃管",
  tungsten: "鎢",
  tv: "電視",
  twin: "綠色雙生子",
  unstable: "不穩定",
  uranium: "鈾",
  uranus: "天王星",
  vanadium: "釩",
  village: "村庄",
  voice: "聲音",
  volcanoes: "火山",
  voyager: "航海家",
  wallpaper: "舊壁紙",
  wear: "用",
  wearing: "穿著",
  weighs: "重",
  weight: "重量",
  welder: "焊工",
  while: "在",
  wilhelm: "威廉",
  woman: "女性",
  won: "贏",
  word: "中文`",
  words: "字",
  wore: "穿",
  worldwide: "全球",
  wrong: "錯了",
  "x-ray": "X光",
  "x-rays": "X光",
  xenon: "氙",
  years: "年",
  ytterbium: "鐿",
  ytterby: "伊特比",
  yttrium: "釔",
  yuri: "尤里",
  zinc: "鋅",
  zirconium: "鋯",

  // 代名詞 / be 動詞
  it: "它", its: "它的", they: "它們", them: "它們", we: "我們", us: "我們",
  our: "我們的", you: "你", your: "你的", i: "我", he: "他", she: "她", who: "誰",
  is: "是", are: "是", was: "曾經是", were: "曾經是", be: "是", am: "是",
  // 冠詞 / 限定詞
  the: "這個", a: "一個", an: "一個", this: "這個", that: "那個", these: "這些",
  those: "那些", some: "一些", any: "任何", all: "全部", every: "每一個", each: "每一個",
  both: "兩個都", few: "少數", many: "很多", much: "很多", more: "更多", most: "最",
  only: "只", also: "也", very: "非常", too: "太", much2: "許多",
  // 介系詞 / 連接詞
  in: "在…裡", on: "在…上", at: "在", of: "的", to: "到", for: "為了", with: "和",
  from: "從", by: "被", as: "作為", into: "進入", inside: "在裡面", outside: "在外面",
  over: "在…上方", under: "在…下面", near: "靠近", after: "在…之後", before: "在…之前",
  when: "當", and: "和", or: "或", but: "但是", so: "所以", because: "因為", than: "比",
  about: "關於", around: "環繞", through: "穿過", up: "向上", down: "向下", out: "外面",
  off: "離開", away: "遠離", again: "再一次", then: "然後", here: "這裡", there: "那裡",
  where: "哪裡", what: "什麼", how: "如何", why: "為什麼", which: "哪一個",
  // 常用動詞
  have: "有", has: "有", had: "有過", do: "做", does: "做", did: "做了",
  make: "製造", makes: "製造", made: "被製造", making: "製造中",
  help: "幫助", helps: "幫助", helped: "幫助過",
  use: "使用", uses: "使用", used: "使用過", using: "正在使用",
  can: "能夠", may: "可能", must: "必須", will: "將會", should: "應該",
  not: "不", like: "像", pipes: "水管", one: "一個",
  keep: "保持", stay: "停留",
  no: "沒有", lets: "讓", let: "讓", rich: "富含", uv: "紫外線",
  his: "他的",
  gives: "給予", give: "給予", given: "被給予",
  take: "拿", takes: "拿", put: "放", puts: "放",
  find: "找到", finds: "找到", found: "發現",
  look: "看", looks: "看起來", see: "看見", sees: "看見", show: "顯示", shows: "顯示",
  work: "運作", works: "運作", worked: "運作過",
  go: "去", goes: "去", come: "來", comes: "來",
  tell: "告訴", tells: "告訴", call: "稱呼", called: "被稱為",
  name: "名字", named: "被命名", honors: "紀念", honor: "紀念",
  contain: "含有", contains: "含有", include: "包含",
  become: "變成", becomes: "變成", turn: "轉變", turns: "轉變",
  protect: "保護", protects: "保護", block: "擋住", blocks: "擋住",
  carry: "傳送", carries: "傳送", send: "傳送", sends: "傳送",
  power: "供電", powers: "供電", drive: "驅動", drives: "驅動",
  glow: "發光", glows: "發光", glowed: "發過光", shine: "閃耀", shines: "閃耀",
  burn: "燃燒", burns: "燃燒", melt: "融化", melts: "融化",
  float: "漂浮", floats: "漂浮", sink: "下沉",
  smell: "聞起來", smells: "聞起來", taste: "嚐起來",
  heal: "癒合", kills: "殺死", kill: "殺死", clean: "清潔", cleans: "清潔",
  last: "持續", lasts: "持續", live: "存在", lives: "存在",
  define: "定義", defines: "定義", mean: "意思是", means: "意思是",
  // 形容詞
  light: "輕的", heavy: "重的", heaviest: "最重的", strong: "堅固的", strongest: "最堅固的",
  hard: "堅硬的", soft: "柔軟的", hot: "熱的", cold: "冷的", warm: "溫暖的",
  big: "大的", small: "小的", tiny: "很小的", large: "大的", little: "小的",
  bright: "明亮的", dark: "黑暗的", clear: "清楚的", clearer: "更清楚的",
  clean2: "乾淨的", dirty: "髒的", safe: "安全的", dangerous: "危險的",
  good: "好的", bad: "壞的", best: "最好的", better: "更好的", well: "很好地",
  fast: "快的", slow: "慢的", high: "高的", low: "低的", long: "長的", short: "短的",
  new: "新的", old: "舊的", young: "年輕的",
  lovely: "漂亮的", pretty: "漂亮的", beautiful: "美麗的", special: "特別的",
  rare: "稀有的", rarest: "最稀有的", costly: "昂貴的", expensive: "昂貴的",
  accurate: "準確的", precise: "精準的", super: "超級的",
  // 顏色
  red: "紅色", blue: "藍色", green: "綠色", yellow: "黃色", white: "白色",
  black: "黑色", orange: "橙色", pink: "粉紅色",
  // 名詞：科學
  element: "元素", elements: "元素", metal: "金屬", metals: "金屬", gas: "氣體",
  gases: "氣體", liquid: "液體", solid: "固體", atom: "原子", atoms: "原子",
  universe: "宇宙", earth: "地球", world: "世界", space: "太空", star: "星星", stars: "星星",
  water: "水", air: "空氣", fire: "火", heat: "熱", ice: "冰", soil: "泥土",
  energy: "能量", electricity: "電", power2: "電力", light2: "光", color: "顏色", colors: "顏色",
  scientist: "科學家", scientists: "科學家", doctor: "醫生", doctors: "醫生",
  research: "研究", lab: "實驗室", laboratory: "實驗室", experiment: "實驗",
  table: "表格", crystal: "結晶", crystals: "結晶", magnet: "磁鐵", magnets: "磁鐵",
  bulb: "燈泡", bulbs: "燈泡", lamp: "燈", lamps: "燈", filament: "燈絲",
  battery: "電池", batteries: "電池", chip: "晶片", chips: "晶片", screen: "螢幕", screens: "螢幕",
  wire: "電線", wires: "電線", machine: "機器", machines: "機器", motor: "馬達", motors: "馬達",
  engine: "引擎", engines: "引擎", train: "列車", trains: "列車", car: "汽車", cars: "汽車",
  plane: "飛機", ship: "船", ships: "太空船", rocket: "火箭", satellite: "人造衛星",
  phone: "手機", phones: "手機", computer: "電腦", camera: "相機", cameras: "相機",
  internet: "網路", signal: "訊號", signals: "訊號", cable: "纜線", cables: "纜線",
  laser: "雷射", lasers: "雷射", xray: "X 光", scan: "檢查", scans: "檢查",
  medicine: "藥", drug: "藥物", hospital: "醫院", body: "身體", skin: "皮膚",
  tooth: "牙齒", teeth: "牙齒", bone: "骨頭", bones: "骨頭", hand: "手", head: "頭",
  food: "食物", milk: "牛奶", water2: "水", nut: "堅果", nuts: "堅果", banana: "香蕉", bananas: "香蕉",
  egg: "蛋", eggs: "蛋", salt: "鹽", sugar: "糖",
  // 名詞：生活
  day: "天", days: "天", time: "時間", second: "秒", minute: "分鐘", hour: "小時",
  year: "年", future: "未來", moment: "一下子", place: "地方", places: "地方",
  house: "房子", houses: "房子", home: "家", school: "學校", city: "城市", state: "州",
  country: "國家", japan: "日本", germany: "德國", russia: "俄羅斯",
  money: "錢", coin: "錢幣", coins: "錢幣", banknote: "鈔票", banknotes: "鈔票",
  jewelry: "珠寶", gem: "寶石", diamond: "鑽石", diamonds: "鑽石", mirror: "鏡子", mirrors: "鏡子",
  paint: "顏料", art: "藝術", artist: "藝術家", artists: "藝術家",
  glass: "玻璃", steel: "鋼", iron: "鐵", gold: "金", silver: "銀", copper: "銅",
  tool: "工具", tools: "工具", part: "零件", parts: "零件", pan: "鍋子", pans: "鍋子",
  can2: "罐子", cans: "罐子", window: "窗戶", windows: "窗戶", door: "門",
  tank: "氣瓶", tanks: "氣瓶", pool: "游泳池", pools: "游泳池",
  match: "火柴", matches: "火柴", candle: "蠟燭", lighter: "打火機", lighters: "打火機",
  clock: "時鐘", clocks: "時鐘", watch: "手錶", watches: "手錶",
  sponge: "海綿", foil: "錫箔紙", rubber: "橡膠", spring: "彈簧", springs: "彈簧",
  fertilizer: "肥料", plant: "植物", tree: "樹", dinosaur: "恐龍", dinosaurs: "恐龍",
  fireworks: "煙火", rainbow: "彩虹", rainbows: "彩虹", spark: "火花", sparks: "火花",
  balloon: "氣球", balloons: "氣球", slime: "黏土", soap: "肥皂", ointment: "藥膏",
  jewelry2: "首飾", implant: "植入物", implants: "植入物", gear: "器材",
  alarm: "警報器", alarms: "警報器", smoke: "煙霧", plant2: "發電廠", plants: "發電廠",
  fuel: "燃料", nuclear: "核能的", radioactive: "放射性的", poisonous: "有毒的",
  solar: "太陽能的", infrared: "紅外線", semiconductor: "半導體", semiconductors: "半導體",
  touch: "觸控", lens: "鏡頭", lenses: "鏡頭", coating: "塗層", catalyst: "觸媒",
  catalysts: "觸媒", exhaust: "廢氣", alloy: "合金", alloys: "合金",
  prize: "獎", nobel: "諾貝爾",
  // 片語用詞
  plus: "加上", made2: "被做成", full: "充滿的", mostly: "大部分",
  together: "一起", everything: "每一件事", something: "某個東西", nothing: "沒有東西",
  never: "從不", always: "總是", often: "常常", sometimes: "有時候",
  forever: "永遠", inside2: "在裡面", outside2: "在外面",
  wrap: "包起來", wraps: "包起來", soak: "吸收", soaks: "吸收",
  scratch: "刮到", scratched: "刮到的", breathe: "呼吸", rust: "生鏽", rusts: "生鏽",
  melt2: "熔化的", melting: "熔化的", point: "點", point2: "溫度",
  enter: "進入", leave: "離開", slowly: "慢慢地", quickly: "快速地",
};

export function lookupWord(raw: string): string | undefined {
  const key = raw.toLowerCase().replace(/[^a-z0-9-]/g, "");
  return DICT[key];
}
